# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from utils import transcribe_audio, generate_summary, extract_action_items
from dotenv import load_dotenv

load_dotenv()

# 1. Load the transcript (for now, working with a sample text file)
with open("transcript.txt", "r", encoding="utf-8") as f:
    transcript = f.read()

# 2. Generate a summary
summary = generate_summary(transcript)
print("\n=== Summary ===\n", summary)

# 3. Extract action items
actions = extract_action_items(transcript)
print("\n=== Action Items ===")
for item in actions:
    print("-", item)