# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import openai
import re

def transcribe_audio(audio_path):
    import whisper
    model = whisper.load_model("base")
    result = model.transcribe(audio_path)
    return result["text"]

def generate_summary(transcript):
    prompt = (
        "Summarize the following meeting transcript into key decisions and insights:\n\n"
        + transcript
    )
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3
    )
    return response["choices"][0]["message"]["content"]

def extract_action_items(transcript):
    pattern = r"\b(?:will|shall|must)\b\s+[^.]+"
    matches = re.findall(pattern, transcript, flags=re.IGNORECASE)
    return matches